# @flutter_tool: use_swift_package_manager=false

platform :ios, '13.0'

# استدعاء ملف التهيئة الرئيسي لـ Flutter من مسار الأداة الفعلي على السيرفر
flutter_root = File.expand_path('..', File.dirname(__FILE__))
if File.exist?(File.join(flutter_root, '.flutter-plugins-dependencies'))
  # تفعيل الدوال الأساسية لـ فلوتر داخل بيئة الماك السحابية
  p_dir = File.dirname(File.expand_path(__FILE__))
  generated_xcode_build_settings_path = File.join(p_dir, 'Flutter', 'generated_xcode_build_settings.rb')
  if File.exist?(generated_xcode_build_settings_path)
    require generated_xcode_build_settings_path
  end
end

# هذا السطر السحري يقوم بعمل جلب وتعريف لكافة دوال فلوتر تلقائياً من الـ SDK المتاح على السيرفر
load File.join(flutter_root, '.flutter-plugins-dependencies') if File.exist?(File.join(flutter_root, '.flutter-plugins-dependencies'))

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # الآن سيتعرف السيرفر على الدالة بنجاح لأننا قمنا بعمل load لملف الإعدادات بالأعلى
  if respond_to?(:flutter_install_all_ios_pods)
    flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_allocations(target) if respond_to?(:flutter_additional_ios_allocations)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end