# @flutter_tool: use_swift_package_manager=false

# Set platform to iOS 13.0
platform :ios, '13.0'

import File.join(File.dirname(File.expand_path(__FILE__)), 'Flutter', 'generated_plugin_pods.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_allocations(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end